### PR TITLE
Trim any extra whitespace

### PR DESCRIPTION
**Pull request by sjparkinson**
There's some annoying whitespace on the landing page.

### CODE REVIEW

**Comment by sjparkinson** [comment]
Ahah, sorry Stuart. We'll roll our own bot that filters by org.

**Comment by iamstuartwilson** [comment]
F off I'm busy yeah?

Also Merry Christmas!

**Comment by sjparkinson** [comment]
> Also Merry Christmas!

:christmas_tree: :santa:

**Comment by leejordan** [comment]
Classic lazy Stuart tbh.

http://devopsreactions.tumblr.com/post/133920623077/css

**Pull request merged**
