### PR TITLE
adds some extra classes to grid panels for more flexible layout options

### PR DESCRIPTION
**Pull request by leejordan**
**Summary**

Adds more options for layout in panel grids

**Notable Changes**

- adds `.grid__panel--alternate` for grey grid panels
- adds `.grid__panel-center` for vertically centered grid panels
- adds `.grid__panel-center--x` for vertically and horizontally centered grid panels
- sets a white background on all grid panel elements as otherwise the page section background shows through
- enforces `text-align-last` usage in buttons to avoid issues when using buttons in flexbox elements such as grid panels

**Upgrade Steps**

all non breaking changes

### CODE REVIEW

**Comment by leejordan** [comment]
@notlee I changed things around based on your (verbal) feedback

**Comment by notlee** [comment]
@leejordan looks good to me but IE9 disagrees!
screen shot 2016-12-16 at 11 26 31

**Comment by notlee** [comment]
Note the difference in the right two panels (image size). Looks better to me but is this intended and could it have a negative impact on shop?
screen shot 2016-12-16 at 16 45 24

**Comment by notlee** [comment]
screen shot 2017-01-03 at 09 40 39

**Pull request merged**
