### PR TITLE
Travis CI notifications for the #pistachio channel

### PR DESCRIPTION
**Pull request by sjparkinson**
🚨 🔔 ✅ or maybe 🙅

### CODE REVIEW

**Comment by notlee** [comment]
@sjparkinson oooooooooooohhhh. The yml looks valid. Two questions:

- Anything I need to do to verify/test?
- Is there any problems making that key public?

**Comment by sjparkinson** [comment]
Key again is encrypted.

Check out the channel and see what you think. It might actually be a bit too noisy, ideally we'd just have notifications for the master branch.

**Comment by sjparkinson** [comment]
Also get the travis cli tool, you can lint the file with `travis lint`.

**Comment by notlee** [comment]
@sjparkinson yeahhh probably a bit much, I'll close this for now.

**Pull request closed without merging**
